# Generated by Django 4.1.1 on 2022-09-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='time_closed',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='time_open',
            new_name='time_start',
        ),
    ]
